# If vars are set to None, nothing will be loaded
CKPT_PATH_GAMMA = None
CKPT_PATH_BDSE = None

#MDBDP/M2DBDP
#CKPT_PATH_BSDE_UZSTEP0 = 'weights/BoundedFNLMDBDPd1nbNeur11nbHL2ndt12030Alpha100BSDE0'
#CKPT_PATH_GAM_UZSTEP0 = 'weights/BoundedFNLMDBDPd1nbNeur11nbHL2ndt12030Alpha100BSDE0'
CKPT_PATH_BSDE_UZSTEP0 = None
CKPT_PATH_GAM_UZSTEP0 = None
CKPT_PATH_BSDE_UZSTEP0_STEPVAL = 1
CKPT_PATH_GAM_UZSTEP0_STEPVAL = 1

#EMDBDP
CKPT_PATH_BSDE_UZDZSTEP0 = 'save_bounded_fnlemdbdp/BoundedFNLEMDBDPd1nbNeur11nbHL2ndt120Alpha100BSDE_0'
CKPT_PATH_BSDE_UZDZSTEP0_STEPVAL = 1

#PWG
CKPT_PATH_BSDE_UZPWGSTEP0 = 'weights/BoundedFNLMDBDPd1nbNeur11nbHL2ndt12030Alpha100BSDE0'
CKPT_PATH_BSDE_UZPWGSTEP0_STEPVAL = 1
